### ISSUE TITLE
Meet the client to specify the client needs

### ISSUE THREAD

**Issue by Sanyi0001** [Digital-Twin-HZ/Digital_Twin#18]

**Comment by Sanyi0001** [comment]
We might want a meeting next week where we discuss what everyone has understood from this meeting, and then we can proceed with the business and data mining goals.

**Comment by amjadhz** [comment]
Complete and the client feedback is written in Wiki [https://github.com/Digital-Twin-HZ/Digital_Twin/wiki/Client-meeting-feedback](url) 21-09-2023
